src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="dtype", type="string")
 * @ORM\DiscriminatorMap({"reservation" = "Reservation",
"reservationTatoo" = "ReservationTatoo","reservationpiercing" = "ReservationPiercing"})
 *
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     *
     */
    private $DateReservation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Etat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $message;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $UnUtilisateur;

	/**
	 * Reservation constructor.
	 * @param $DateReservation
	 * @param $Etat
	 * @param $message
	 * @param $UnUtilisateur
	 */
	public function __construct($DateReservation, $Etat, $message, $UnUtilisateur)
	{
		$this->DateReservation = $DateReservation;
		$this->Etat = $Etat;
		$this->message = $message;
		$this->UnUtilisateur = $UnUtilisateur;
	}


	public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateReservation()
    {
        return $this->DateReservation;
    }

    public function setDateReservation($DateReservation): self
    {
        $this->DateReservation = $DateReservation;

        return $this;
    }

    public function getEtat()
    {
        return $this->Etat;
    }

    public function setEtat($Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getUnUtilisateur()
    {
        return $this->UnUtilisateur;
    }

    public function setUnUtilisateur( $UnUtilisateur): self
    {
        $this->UnUtilisateur = $UnUtilisateur;

        return $this;
    }

	public function __toString()
	{
		return strval($this->id);
	}
}

src/Controller/BackOfficeController.php
<?php

namespace App\Controller;

use App\Entity\Achat;
use App\Entity\Article;
use App\Entity\Category;
use App\Entity\Produit;
use App\Entity\Realisation;
use App\Entity\Reservation;
use App\Entity\Utilisateur;
use App\Form\ArticleType;
use App\Form\CategorieType;
use App\Form\ProduitType;
use App\Form\RealisationType;
use App\Form\ReportRdvType;
use App\Notification\MailNotification;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Validation;


class BackOfficeController extends AbstractController
{
    /**
     * @Route("/back/office", name="back_office")
     * @IsGranted("ROLE_ADMIN")
     */
    public function index(): Response
    {
    	/*Last Rdv*/
	    $em = $this->getDoctrine()->getManager();
	    $lastRdv = $em->getRepository(Reservation::class)->findLast();
	    $lastId = $em->getRepository(Reservation::class)->findIdlast();
	    if (!empty($lastId)){
		    $lastId = $lastId[0]['id'];
	    }
	    $rea= $em->getRepository(Realisation::class)->findAll();
	    $prod= $em->getRepository(Produit::class)->findAll();
	    $art= $em->getRepository(Article::class)->findAll();
	    $ach= $em->getRepository(Achat::class)->findLast();
	    $client = "";
	    if(!empty($lastRdv)){
		    $client = $em->getRepository(Utilisateur::class)->find($lastRdv["0"]["un_utilisateur_id"]);
	    }

        return $this->render('back_office/index.html.twig', [
            'controller_name' => 'BackOfficeController',
	        "lastRdv"=>$lastRdv,
	        'client'=>$client,
	        "rea"=>$rea,
	        'produit' =>$prod,
	        'article' =>$art,
	        "achat"=>$ach,
	        'lastId'=>$lastId
        ]);
    }


///////////////////////////////////////////////
/// Gestion boutique
///////////////////////////////////////////////
	/**
	 * @Route("/back/office/AjoutProduit", name="back_office_ajout_produit")
	 * @IsGranted("ROLE_ADMIN")
	 */
	public function product(Request $request): Response
	{
		$Product = new Produit();
		$form = $this->createForm(ProduitType::class,$Product);
		$form->handleRequest($request);
		if ($form->isSubmitted() && $form->isValid()){
			$Product= $form->getData();
			$Product = $Product->setPrix($form->get('prix')->getData()*1.014+0.25);
			$entityManager = $this->getDoctrine()->getManager();
			$entityManager->persist($Product);
			$entityManager->flush();
			return $this->redirectToRoute('back_office',[]);
		}

		$categ = new Category();
		$formC = $this->createForm(CategorieType::class,$categ);
		$error=[];

		$formC->handleRequest($request);
		if ($formC->isSubmitted() && $formC->isValid()){
				$categ->setLibelle($formC->get("libelle")->getData());
				$entityManager = $this->getDoctrine()->getManager();
				$entityManager->persist($categ);
				$entityManager->flush();
		}

		return $this->render('back_office/product.html.twig', [
			'controller_name' => 'BackOfficeController',
			'form' => $form->createView(),
			'formC' => $formC->createView(),
			"error"=>$error
		]);
	}

	/**
	 * @Route("/back/office/DelProduit/{id}", name="back_office_produitDel")
	 * @IsGranted("ROLE_ADMIN")
	 */
	public function productD($id)
	{
		$em = $this->getDoctrine()->getManager();
		$Product = $em->getRepository(Produit::class)->find($id);
		$achats = $em->getRepository(Achat::class)->findByProduct($Product->getId());

			if (empty($achats)){
				$em->remove($Product);
				$em->flush();
				return $this->redirectToRoute('back_office',[]);

			}
			else {
				return $this->redirectToRoute('back_office',[]);
			}
		return $this->redirectToRoute('back_office',[]);
	}

    /**
     * @Route("/back/office/TousLesProduits", name="back_office_allP")
     * @IsGranted("ROLE_ADMIN")
     */
    public function productAll()
    {
        $em = $this->getDoctrine()->getManager();
        $Product = $em->getRepository(Produit::class)->findAll();
        return $this->render('back_office/lesProduits.html.twig', [
            'controller_name' => 'BackOfficeController',
            'produits' => $Product,
        ]);
    }

	/**
	 * @Route("/back/office/ModProduit/{id}", name="back_office_ajout_produitMod")
	 * @IsGranted("ROLE_ADMIN")
	 */
	public function productM(Request $request,$id): Response
	{
		$em = $this->getDoctrine()->getManager();
		$Product = $em->getRepository(Produit::class)->find($id);
		$form = $this->createForm(ProduitType::class,$Product);
		$form->handleRequest($request);
		if ($form->isSubmitted() && $form->isValid()){
			$Product= $form->getData();
			$entityManager = $this->getDoctrine()->getManager();
			$entityManager->persist($Product);
			$entityManager->flush();
			return $this->redirectToRoute('back_office',[]);
		}
		return $this->render('back_office/Modproduct.html.twig', [
			'controller_name' => 'BackOfficeController',
			'form' => $form->createView(),
		]);
	}

	/**
	 * @Route("/back/office/gestionAchat", name="back_office_gestion_achat")
	 * @IsGranted("ROLE_ADMIN")
	 */
	public function gestionAchat(Request $request): Response
	{
		$em = $this->getDoctrine()->getManager();
		$AllAchat = $em->getRepository(Achat::class)->findAll();

		return $this->render('back_office/gestionAchat.html.twig', [
			'controller_name' => 'BackOfficeController',
			'achats' => $AllAchat
		]);
	}

	/**
	 * @Route("/back/office/archives", name="back_office_gestion_archive")
	 * @IsGranted("ROLE_ADMIN")
	 */
	public function archive(Request $request): Response
	{
		$em = $this->getDoctrine()->getManager();
		$AllAchat = $em->getRepository(Achat::class)->findAll();

		return $this->render('back_office/archive.html.twig', [
			'controller_name' => 'BackOfficeController',
			'achats' => $AllAchat
		]);
	}


	/**
	 * @Route("/back/office/donner/{id}", name="back_office_donner")
	 * @IsGranted("ROLE_ADMIN")
	 */
	public function donner($id, MailNotification $mail): Response
	{
		$em = $this->getDoctrine()->getManager();
		$ach = $em->getRepository(Achat::class)->find($id);
		$user = $em->getRepository(Utilisateur::class)->find($ach->getLeUtilisateur());

		$ach->setRecu("recu");

		$em->persist($ach);
		$em->flush();
		$mail->notifyContact("Votre produit est en votre possession  ! ",$user->getMail(),"Merci de votre achat..","Détail de l'achat: ".$ach->getDescriptionAchat());




		return $this->redirectToRoute('back_office_gestion_achat',[]);
	}

	/**
	 * @Route("/back/office/livrer/{id}", name="back_office_livrer")
	 * @IsGranted("ROLE_ADMIN")
	 */
	public function livré($id, MailNotification $mail): Response
	{
		$em = $this->getDoctrine()->getManager();
		$ach = $em->getRepository(Achat::class)->find($id);
		$user = $em->getRepository(Utilisateur::class)->find($ach->getLeUtilisateur());

		$ach->setRecu("livrer");

		$em->persist($ach);
		$em->flush();
		$mail->notifyContact("Votre produit a étais expédier  ! ",$user->getMail(),"Il ne vous reste plus qu'attendre votre produit.","Détail de l'achat: ".$ach->getDescriptionAchat());



		return $this->redirectToRoute('back_office_gestion_achat',[]);
	}

	/**
	 * @Route("/back/office/produit/salon/{id}", name="back_office_salon")
	 * @IsGranted("ROLE_ADMIN")
	 */
	public function salon($id, MailNotification $mail): Response
	{
		$em = $this->getDoctrine()->getManager();
		$ach = $em->getRepository(Achat::class)->find($id);
		$user = $em->getRepository(Utilisateur::class)->find($ach->getLeUtilisateur());
		$ach->setRecu("salon");
		$em->persist($ach);
		$em->flush();
		$mail->notifyContact("Récupèrer votre produit au salon ! ",$user->getMail(),"","Détail de l'achat: ".$ach->getDescriptionAchat());

		return $this->redirectToRoute('back_office_gestion_achat',[]);
	}


	///////////////////////////////////////////////
	/// Fin Gestion boutique
	///////////////////////////////////////////////



	///////////////////////////////////////////////
	/// Gestion Article
	///////////////////////////////////////////////

	/**
	 * @Route("/back/office/AjoutArticle", name="back_office_ajout_article")
	 * @IsGranted("ROLE_ADMIN")
	 */
	public function article(Request $request, MailNotification $mail): Response
	{
		$art = new Article();
		$form = $this->createForm(ArticleType::class,$art);
		$form->handleRequest($request);
		if ($form->isSubmitted() && $form->isValid()){
			$art = $form->getData();
			$entityManager = $this->getDoctrine()->getManager();
			$entityManager->persist($art);
			$entityManager->flush();
			$utilisateur =$entityManager->getRepository(Utilisateur::class)->findAll();
			foreach ($utilisateur as $user){
				$mail->notifyContact("Nouvel article ! ",$user->getMail(),"Un nouvel article à été ajouter !","Détail de l'article: ".$art->getDescription());
			}

			return $this->redirectToRoute('back_office',[]);
		}
		return $this->render('back_office/article.html.twig', [
			'controller_name' => 'BackOfficeController',
			'form' => $form->createView(),
		]);

	}

	/**
	 * @Route("/back/office/DelArticle/{id}", name="back_office_ajout_articleDel")
	 * @IsGranted("ROLE_ADMIN")
	 */
	public function artD($id): Response
	{
		$em = $this->getDoctrine()->getManager();
		$art = $em->getRepository(Article::class)->find($id);
		$em->remove($art);
		$em->flush();

		return $this->redirectToRoute('back_office',[]);
	}

	/**
	 * @Route("/back/office/ModArticle/{id}", name="back_office_ajout_articleMod")
	 * @IsGranted("ROLE_ADMIN")
	 */
	public function artM(Request $request,$id): Response
	{
		$em = $this->getDoctrine()->getManager();
		$art = $em->getRepository(Article::class)->find($id);
		$form = $this->createForm(ArticleType::class,$art);
		$form->handleRequest($request);
		if ($form->isSubmitted() && $form->isValid()){
			$art= $form->getData();

templates/back_office/ModArticle.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <style>
        label[for=article_imageFile_delete]{
            display: none;
        }
        #article_imageFile_delete{
            visibility: hidden;
            margin-bottom: 20px;
        }
        @media screen and (max-width: 640px){
            input[type='file'] {
                color: transparent;
                margin-left: 11%;
            }
        }
    </style>
<section>
    <div class="-mt-4">
        {% include('backOffice.html.twig') %}
        <div class="flex-1 flex flex-col overflow-hidden">
            <header class="flex justify-between items-center py-4 px-6 bg-white border-b-4 border-nav-light">
                <div class="flex items-center">
                    <button @click="sidebarOpen = true" class="text-gray-500 focus:outline-none lg:hidden">
                        <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M4 6H20M4 12H20M4 18H11" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                  stroke-linejoin="round"></path>
                        </svg>
                    </button>
                </div>
            </header>
            <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
                <div class="container mx-auto px-6 py-8">
                    <h3 class="text-gray-700 text-3xl font-medium">Ajout de Produit</h3>

                    <div class="mt-4 bg-white rounded">
                        <div class="container mx-auto text-center">
                            <article class="py-12 px-4 ml-4">
                                <h1 class="text-2xl text-center mb-4 font-semibold font-heading font-semibold">Formulaire de modification de produit.</h1>
                                <hr>
                                <div class="container w-8/12 mx-auto">
                                    {{ form_start(form) }}
                                    <div class="flex flex-col pt-4">
                                        <label for="text" class="text-lg">titre de l'article</label>
                                        {{ form_widget(form.titre, {'attr': {'class': 'appearance-none border border-gray-200 p-2 focus:outline-none focus:border-gray-500' ,
                                            'placeholder': 'Titre' }}) }}
                                    </div>

                                    <div class="flex flex-col pt-4">
                                        <label for="text" class="text-lg">Description de l'article</label>
                                        {{ form_widget(form.description, {'attr': {'class': 'appearance-none border border-gray-200 p-2 focus:outline-none focus:border-gray-500' ,
                                            'placeholder': 'description' }}) }}
                                    </div>

                                    <div class="flex flex-col pt-4">
                                        <label for="text" class="text-lg">Image de l'article</label>
                                        {{ form_widget(form.imageFile)}}
                                    </div>
                                    <input type="submit" value="Ajouter Article" class="bg-black text-white font-bold text-lg hover:bg-gray-700 p-2 mt-8">
                                    {{ form_end(form) }}
                                </div>
                            </article>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
    </div>
</section>
{% endblock %}

templates/back_office/article.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <style>
        @media screen and (max-width: 640px){
            input[type='file'] {
                color: transparent;
                margin-left: 11%;
            }
        }
    </style>
<section>
    <div class="-mt-4">
        {% include('backOffice.html.twig') %}
        <div class="flex-1 flex flex-col overflow-hidden">
            <header class="flex justify-between items-center py-4 px-6 bg-white border-b-4 border-nav-light">
                <div class="flex items-center">
                    <button @click="sidebarOpen = true" class="text-gray-500 focus:outline-none lg:hidden">
                        <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M4 6H20M4 12H20M4 18H11" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                  stroke-linejoin="round"></path>
                        </svg>
                    </button>
                </div>
            </header>
            <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
                <div class="container mx-auto px-6 py-8">
                    <h3 class="text-gray-700 text-3xl font-medium">Ajout de Produit</h3>

                    <div class="mt-4 bg-white rounded">
                        <div class="container mx-auto text-center">
                            <article class="py-12 px-4 ml-4">
                                <h1 class="text-2xl text-center mb-4 font-semibold font-heading font-semibold">Formulaire de modification de produit.</h1>
                                <hr>
                                <div class="container w-8/12 mx-auto">
                                    {{ form_start(form) }}
                                    <div class="flex flex-col pt-4">
                                        <label for="text" class="text-lg">titre de l'article</label>
                                        {{ form_widget(form.titre, {'attr': {'class': 'appearance-none border border-gray-200 p-2 focus:outline-none focus:border-gray-500' ,
                                            'placeholder': 'Titre' }}) }}
                                    </div>

                                    <div class="flex flex-col pt-4">
                                        <label for="text" class="text-lg">Description de l'article</label>
                                        {{ form_widget(form.description, {'attr': {'class': 'appearance-none border border-gray-200 p-2 focus:outline-none focus:border-gray-500' ,
                                            'placeholder': 'description' }}) }}
                                    </div>

                                    <div class="flex flex-col pt-4">
                                        <label for="text" class="text-lg">Image de l'article</label>
                                        {{ form_widget(form.imageFile)}}
                                    </div>
                                    <input type="submit" value="Ajouter Article" class="bg-black text-white font-bold text-lg hover:bg-gray-700 p-2 mt-8">
                                    {{ form_end(form) }}
                                </div>
                            </article>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
    </div>
</section>
{% endblock %}

templates/back_office/gestionR.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <style>
        @media screen and (max-width: 640px) {
            input[type='file'] {
                color: transparent;
                margin-left: 11%;
            }
        }
    </style>
    <section>
        <div class="-mt-4">
            {% include('backOffice.html.twig') %}
            <div class="flex-1 flex flex-col overflow-hidden">
                <header class="flex justify-between items-center py-4 px-6 bg-white border-b-4 border-nav-light">
                    <div class="flex items-center">
                        <button @click="sidebarOpen = true" class="text-gray-500 focus:outline-none lg:hidden">
                            <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M4 6H20M4 12H20M4 18H11" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                      stroke-linejoin="round"></path>
                            </svg>
                        </button>
                    </div>
                </header>
                <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
                    <div class="container mx-auto px-6 py-8">
                        <h3 class="text-gray-700 text-3xl font-medium">Gestion des rendez-vous.</h3>

                        <div class="mt-4 bg-white rounded">
                            <div class="container mx-auto text-center">
                                <article class="py-12 px-4 ml-4">
                                    <h1 class="text-2xl text-center mb-4 font-semibold font-heading font-semibold"></h1>
                                    <hr>
                                    <div class="container w-8/12 mx-auto">
                                        <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 pr-10 lg:px-8">
                                            <div class="align-middle inline-block min-w-full shadow overflow-hidden bg-white shadow-dashboard px-8 pt-3 rounded-bl-lg rounded-br-lg">
                                                <table class="min-w-full">
                                                    <thead>
                                                    <tr>
                                                        <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">Client</th>
                                                        <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">Majeur</th>
                                                        <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">Mail</th>
                                                        <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">Téléphone</th>
                                                        <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">Status</th>
                                                        <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">Allergie</th>
                                                        <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">Partie Corps</th>
                                                        <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">Type Rendez-vous</th>
                                                        <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">Date Réservation
                                                        </th>
                                                        <th class="px-6 py-3 border-b-2 border-gray-300"></th>
                                                    </tr>
                                                    </thead>
                                                    <tbody class="bg-white">
                                                    {% if rdvs is not empty %}
                                                        {% for rdv in rdvs %}
                                                            <tr>
                                                                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-500">
                                                                    <div class="text-sm leading-5 text-blue-900">{{ rdv.UnUtilisateur
                                                                        .nom }} {{ rdv.UnUtilisateur
                                                                        .prenom }}</div>
                                                                </td>
                                                                <td class="px-6 py-4 whitespace-no-wrap border-b text-blue-900 border-gray-500 text-sm leading-5">{% if rdv.UnUtilisateur.majeur ==
                                                                        true  %}Oui{% else %}Non{% endif %}</td>
                                                                <td class="px-6 py-4 whitespace-no-wrap border-b text-blue-900 border-gray-500 text-sm leading-5">{{ rdv.UnUtilisateur
                                                                    .mail }}</td>
                                                                <td class="px-6 py-4 whitespace-no-wrap border-b text-blue-900 border-gray-500 text-sm leading-5">{{ rdv.UnUtilisateur
                                                                    .telephone }}</td>
                                                                <td class="px-6 py-4 whitespace-no-wrap border-b text-blue-900 border-gray-500 text-sm leading-5">
                                                                    <span class="relative inline-block px-3 py-1 font-semibold text-green-900 leading-tight">
                                                                        <span aria-hidden class="absolute inset-0 bg-green-200 opacity-50 rounded-full"></span>
                                                                        <span class="relative {% if rdv.etat == "valider" %} text-vert{% else %} text-rouge {% endif %}  text-xs">{{ rdv.Etat }}</span>
                                                                    </span>
                                                                </td>
                                                                <td class="px-6 py-4 whitespace-no-wrap border-b text-blue-900 border-gray-500 text-sm leading-5">
                                                                    <span class="relative inline-block px-3 py-1 font-semibold text-green-900 leading-tight">
                                                                        <span aria-hidden class="absolute inset-0 bg-green-200 opacity-50 rounded-full"></span>
                                                                        <span class="relative  text-textC">{{ rdv.allergie }}</span>
                                                                    </span>
                                                                </td>
                                                                <td class="px-6 py-4 whitespace-no-wrap border-b text-blue-900 border-gray-500 text-sm leading-5">
                                                                    <span class="relative inline-block px-3 py-1 font-semibold text-green-900 leading-tight">
                                                                        <span aria-hidden class="absolute inset-0 bg-green-200 opacity-50 rounded-full"></span>
                                                                        <span class="relative  text-textC">{{ rdv.partieCorps }}</span>
                                                                    </span>
                                                                </td>
                                                                <td class="px-6 py-4 whitespace-no-wrap border-b text-blue-900 border-gray-500 text-sm leading-5">
                                                                    <span class="relative inline-block px-3 py-1 font-semibold text-green-900 leading-tight">
                                                                        <span aria-hidden class="absolute inset-0 bg-green-200 opacity-50 rounded-full"></span>
                                                                        <span class="relative  text-textC">{% if rdv.taille is empty %} Piercing {% else %} Tatouage {% endif %} </span>
                                                                    </span>
                                                                </td>
                                                                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-500 text-blue-900 text-sm leading-5">{{ rdv.DateReservation|date
                                                                        ('d m Y H:i') }} h</td>
                                                                <td class="px-6 py-4 flex flex-col whitespace-no-wrap text-right border-b border-gray-500 text-sm leading-5">
                                                                    <a href="{{ path('back_office_valider', {"id": rdv.id }) }}" class="mt-1 px-5 py-2 border-vert border text-vert rounded
                                                        transition
                                                        duration-300
                                                        hover:bg-vert
                                                        hover:text-white focus:outline-none ">Valider</a>
                                                                    <a href="{{ path('back_office_annulers', {"id": rdv.id }) }}" class="mt-1 px-5 py-2 border-indigo-500 border text-indigo-500
                                                                    rounded
                                                        transition duration-300 hover:bg-indigo-500
                                                         hover:text-white focus:outline-none">Annuler</a>
                                                                    <a href="{{ path('back_office_modify', {"id": rdv.id }) }}" class="mt-1 px-5 py-2 border-nav-dark border text-yellow-600
                                                                    rounded
                                                        transition duration-300 hover:bg-btnBack
                                                         hover:text-white focus:outline-none">reporter</a>

                                                                    <a href="{{ path('back_office_delete', {"id": rdv.id }) }}" class="mt-1 px-5 py-2 border-rouge border text-red-500 rounded
                                                        transition duration-300 hover:bg-rouge
                                                         hover:text-white focus:outline-none">Suprimer</a>
                                                                </td>
                                                            </tr>

                                                        {% endfor %}
                                                    {% else %}
                                                        <p>Aucun rendez-vous pour le moment</p>
                                                    {% endif %}
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </article>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </div>
        </div>
    </section>
{% endblock %}